// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailor360.Modules.Billing.Infrastructure.Persistence;

#nullable disable

namespace Tailor360.Modules.Billing.Infrastructure.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260912064102_PriceLists")]
    partial class PriceLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.DiscountRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("discount_rule_key");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<decimal>("Maximum")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("maximum");

                    b.Property<decimal>("MaximumWithoutApproval")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("maximum_without_approval");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PriceListVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_version_id");

                    b.HasKey("Id")
                        .HasName("pk_discount_rules");

                    b.HasIndex("PriceListVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_discount_rules_version_code");

                    b.HasIndex("PriceListVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_discount_rules_version_key");

                    b.ToTable("discount_rules", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_discount_rules_bounds_are_ordered", "maximum_without_approval >= 0 AND maximum_without_approval <= maximum");

                            t.HasCheckConstraint("ck_discount_rules_code_is_well_formed", "code ~ '^[A-Z][A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_price_lists");

                    b.HasIndex("OrganisationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_price_lists_organisation_code");

                    b.ToTable("price_lists", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_price_lists_code_is_well_formed", "code ~ '^[A-Z][A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.PriceListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("base_rate");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_item_key");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PriceListVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_version_id");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tax_code");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_price_list_items");

                    b.HasIndex("PriceListVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_price_list_items_version_code");

                    b.HasIndex("PriceListVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_price_list_items_version_key");

                    b.ToTable("price_list_items", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_price_list_items_code_is_well_formed", "code ~ '^[A-Z][A-Z0-9_]+$'");

                            t.HasCheckConstraint("ck_price_list_items_rate_is_not_negative", "base_rate >= 0");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.PriceListVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClonedFromVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloned_from_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<decimal>("OverrideThresholdPercent")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("override_threshold_percent");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid")
                        .HasColumnName("price_list_id");

                    b.Property<string>("PublishReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publish_reason");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retired_at");

                    b.Property<Guid?>("RetiredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("retired_by");

                    b.Property<string>("RetiredReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("retired_reason");

                    b.Property<int>("RoundOff")
                        .HasColumnType("integer")
                        .HasColumnName("round_off");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TaxInclusive")
                        .HasColumnType("boolean")
                        .HasColumnName("tax_inclusive");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_price_list_versions");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("ix_price_list_versions_organisation_status");

                    b.HasIndex("PriceListId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_price_list_versions_list_number");

                    b.ToTable("price_list_versions", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_price_list_versions_lifecycle_is_consistent", "(status = 0 AND published_at IS NULL AND retired_at IS NULL)\nOR (status = 1 AND published_at IS NOT NULL AND retired_at IS NULL)\nOR (status = 2 AND published_at IS NOT NULL AND retired_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_price_list_versions_number_is_positive", "version_number >= 1");

                            t.HasCheckConstraint("ck_price_list_versions_threshold_is_a_percentage", "override_threshold_percent >= 0 AND override_threshold_percent <= 100");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Registrations.GstRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("Gstin")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(true)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("gstin");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_gst_registrations");

                    b.HasIndex("OrganisationId", "BranchId", "EffectiveFrom")
                        .HasDatabaseName("ix_gst_registrations_branch_effective_from");

                    b.ToTable("gst_registrations", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_gst_registrations_dates_are_ordered", "effective_to IS NULL OR effective_to >= effective_from");

                            t.HasCheckConstraint("ck_gst_registrations_gstin_shape", "gstin ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]$'");

                            t.HasCheckConstraint("ck_gst_registrations_state_code_shape", "state_code ~ '^[0-9]{2}$'");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Tax.TaxCode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(true)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("classification");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_code_key");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("TaxConfigurationVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("tax_configuration_version_id");

                    b.HasKey("Id")
                        .HasName("pk_tax_codes");

                    b.HasIndex("TaxConfigurationVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_codes_version_code");

                    b.HasIndex("TaxConfigurationVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_codes_version_key");

                    b.ToTable("tax_codes", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_tax_codes_classification_is_digits", "classification ~ '^[0-9]{4,8}$'");

                            t.HasCheckConstraint("ck_tax_codes_code_is_well_formed", "code ~ '^[A-Z][A-Z0-9_]+$'");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Tax.TaxConfigurationVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClonedFromVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloned_from_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PublishReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("publish_reason");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retired_at");

                    b.Property<Guid?>("RetiredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("retired_by");

                    b.Property<string>("RetiredReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("retired_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tax_configuration_versions");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("ix_tax_configuration_versions_organisation_status");

                    b.HasIndex("OrganisationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_tax_configuration_versions_organisation_number");

                    b.ToTable("tax_configuration_versions", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_tax_configuration_versions_lifecycle_is_consistent", "(status = 0 AND published_at IS NULL AND retired_at IS NULL)\nOR (status = 1 AND published_at IS NOT NULL AND retired_at IS NULL)\nOR (status = 2 AND published_at IS NOT NULL AND retired_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_tax_configuration_versions_number_is_positive", "version_number >= 1");
                        });
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "billing");
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("AvailableAt", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "billing");
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.DiscountRule", b =>
                {
                    b.HasOne("Tailor360.Modules.Billing.Domain.Pricing.PriceListVersion", null)
                        .WithMany("DiscountRules")
                        .HasForeignKey("PriceListVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_discount_rules_price_list_versions_price_list_version_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.PriceListItem", b =>
                {
                    b.HasOne("Tailor360.Modules.Billing.Domain.Pricing.PriceListVersion", null)
                        .WithMany("Items")
                        .HasForeignKey("PriceListVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_list_items_price_list_versions_price_list_version_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.PriceListVersion", b =>
                {
                    b.HasOne("Tailor360.Modules.Billing.Domain.Pricing.PriceList", null)
                        .WithMany()
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_list_versions_price_lists_price_list_id");

                    b.OwnsMany("Tailor360.Modules.Billing.Domain.Pricing.PriceListVersionBranch", "Branches", b1 =>
                        {
                            b1.Property<Guid>("PriceListVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("price_list_version_id");

                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("branch_id");

                            b1.HasKey("PriceListVersionId", "BranchId")
                                .HasName("pk_price_list_version_branches");

                            b1.ToTable("price_list_version_branches", "billing");

                            b1.WithOwner()
                                .HasForeignKey("PriceListVersionId")
                                .HasConstraintName("fk_price_list_version_branches_price_list_versions");
                        });

                    b.Navigation("Branches");
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Tax.TaxCode", b =>
                {
                    b.HasOne("Tailor360.Modules.Billing.Domain.Tax.TaxConfigurationVersion", null)
                        .WithMany("TaxCodes")
                        .HasForeignKey("TaxConfigurationVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tax_codes_tax_configuration_versions");

                    b.OwnsMany("Tailor360.Modules.Billing.Domain.Tax.TaxComponent", "Components", b1 =>
                        {
                            b1.Property<Guid>("TaxCodeId")
                                .HasColumnType("uuid")
                                .HasColumnName("tax_code_id");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("kind");

                            b1.Property<decimal>("RatePercent")
                                .HasPrecision(6, 3)
                                .HasColumnType("numeric(6,3)")
                                .HasColumnName("rate_percent");

                            b1.HasKey("TaxCodeId", "Kind")
                                .HasName("pk_tax_components");

                            b1.ToTable("tax_components", "billing", t =>
                                {
                                    t.HasCheckConstraint("ck_tax_components_rate_is_a_percentage", "rate_percent >= 0 AND rate_percent <= 100");
                                });

                            b1.WithOwner()
                                .HasForeignKey("TaxCodeId")
                                .HasConstraintName("fk_tax_components_tax_codes_tax_code_id");
                        });

                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Pricing.PriceListVersion", b =>
                {
                    b.Navigation("DiscountRules");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Tailor360.Modules.Billing.Domain.Tax.TaxConfigurationVersion", b =>
                {
                    b.Navigation("TaxCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
