// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailor360.Modules.Media.Infrastructure.Persistence;

#nullable disable

namespace Tailor360.Modules.Media.Infrastructure.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("media")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaAccessLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accessed_at");

                    b.Property<Guid>("AccessedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accessed_by");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("MediaObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_object_id");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.HasKey("Id")
                        .HasName("pk_media_access_log");

                    b.HasIndex("MediaObjectId", "AccessedAt")
                        .HasDatabaseName("ix_media_access_log_object_accessed");

                    b.ToTable("media_access_log", "media");
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaDerivative", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("HeightPx")
                        .HasColumnType("integer")
                        .HasColumnName("height_px");

                    b.Property<Guid>("MediaObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_object_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Variant")
                        .HasColumnType("integer")
                        .HasColumnName("variant");

                    b.Property<int>("WidthPx")
                        .HasColumnType("integer")
                        .HasColumnName("width_px");

                    b.HasKey("Id")
                        .HasName("pk_media_derivatives");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_derivatives_object_key");

                    b.HasIndex("MediaObjectId", "Variant")
                        .IsUnique()
                        .HasDatabaseName("ux_media_derivatives_object_variant");

                    b.ToTable("media_derivatives", "media", t =>
                        {
                            t.HasCheckConstraint("ck_media_derivatives_dimensions_are_positive", "width_px > 0 AND height_px > 0");

                            t.HasCheckConstraint("ck_media_derivatives_size_is_positive", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaObject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alt_text");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character(64)")
                        .HasColumnName("checksum")
                        .IsFixedLength();

                    b.Property<int>("Classification")
                        .HasColumnType("integer")
                        .HasColumnName("classification");

                    b.Property<Guid?>("ConsentRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("consent_record_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<DateOnly?>("RetentionDate")
                        .HasColumnType("date")
                        .HasColumnName("retention_date");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_media_objects");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_media_objects_customer");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_media_objects_job");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_objects_object_key");

                    b.HasIndex("RetentionDate")
                        .HasDatabaseName("ix_media_objects_retention_date");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("ix_media_objects_organisation_status");

                    b.ToTable("media_objects", "media", t =>
                        {
                            t.HasCheckConstraint("ck_media_objects_alt_text_required_for_diagrams", "purpose NOT IN (2, 3) OR alt_text IS NOT NULL");

                            t.HasCheckConstraint("ck_media_objects_checksum_is_well_formed", "checksum ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_media_objects_size_is_positive", "size_bytes > 0");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaQuarantineEntry", b =>
                {
                    b.Property<Guid>("MediaObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_object_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("QuarantineKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("quarantine_key");

                    b.Property<int?>("ScanOutcome")
                        .HasColumnType("integer")
                        .HasColumnName("scan_outcome");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scanned_at");

                    b.HasKey("MediaObjectId")
                        .HasName("pk_media_quarantine");

                    b.ToTable("media_quarantine", "media", t =>
                        {
                            t.HasCheckConstraint("ck_media_quarantine_attempt_count_is_not_negative", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaRetentionHold", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MediaObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_object_id");

                    b.Property<DateTimeOffset>("PlacedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("placed_at");

                    b.Property<Guid>("PlacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("placed_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("released_at");

                    b.Property<Guid?>("ReleasedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("released_by");

                    b.HasKey("Id")
                        .HasName("pk_media_retention_holds");

                    b.HasIndex("MediaObjectId", "ReleasedAt")
                        .HasDatabaseName("ix_media_retention_holds_object_released");

                    b.ToTable("media_retention_holds", "media", t =>
                        {
                            t.HasCheckConstraint("ck_media_retention_holds_release_is_ordered", "released_at IS NULL OR released_at >= placed_at");
                        });
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "media");
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("AvailableAt", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "media");
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaDerivative", b =>
                {
                    b.HasOne("Tailor360.Modules.Media.Domain.Media.MediaObject", null)
                        .WithMany()
                        .HasForeignKey("MediaObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_derivatives_media_objects_media_object_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaQuarantineEntry", b =>
                {
                    b.HasOne("Tailor360.Modules.Media.Domain.Media.MediaObject", null)
                        .WithOne()
                        .HasForeignKey("Tailor360.Modules.Media.Domain.Media.MediaQuarantineEntry", "MediaObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_quarantine_media_objects_media_object_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Media.Domain.Media.MediaRetentionHold", b =>
                {
                    b.HasOne("Tailor360.Modules.Media.Domain.Media.MediaObject", null)
                        .WithMany()
                        .HasForeignKey("MediaObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_retention_holds_media_objects_media_object_id");
                });
#pragma warning restore 612, 618
        }
    }
}
