// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailor360.Modules.Catalog.Infrastructure.Persistence;

#nullable disable

namespace Tailor360.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailor360.Modules.Catalog.Domain.Catalogue.CatalogVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClonedFromVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloned_from_version_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PublishReason")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("publish_reason");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("retired_at");

                    b.Property<Guid?>("RetiredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("retired_by");

                    b.Property<string>("RetiredReason")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("retired_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_catalog_versions");

                    b.HasIndex("OrganisationId")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_versions_one_published")
                        .HasFilter("status = 1");

                    b.HasIndex("OrganisationId", "Status")
                        .HasDatabaseName("ix_catalog_versions_organisation_status");

                    b.HasIndex("OrganisationId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_versions_organisation_number");

                    b.ToTable("catalog_versions", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_catalog_versions_lifecycle_is_consistent", "(status = 0 AND published_at IS NULL AND retired_at IS NULL)\nOR (status = 1 AND published_at IS NOT NULL AND retired_at IS NULL)\nOR (status = 2 AND published_at IS NOT NULL AND retired_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_catalog_versions_number_is_positive", "version_number >= 1");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Catalog.Domain.Catalogue.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("active_from");

                    b.Property<DateOnly?>("ActiveTo")
                        .HasColumnType("date")
                        .HasColumnName("active_to");

                    b.Property<Guid>("CatalogVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_version_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("FeatureFlagKey")
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("feature_flag_key");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("category_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_tamil");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent");

                    b.HasIndex("CatalogVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_version_code");

                    b.HasIndex("CatalogVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_version_key");

                    b.ToTable("categories", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_categories_active_dates_are_ordered", "active_from IS NULL OR active_to IS NULL OR active_to >= active_from");

                            t.HasCheckConstraint("ck_categories_code_is_well_formed", "code ~ '^[A-Z][A-Z0-9_]*$'");

                            t.HasCheckConstraint("ck_categories_display_order_is_not_negative", "display_order >= 0");

                            t.HasCheckConstraint("ck_categories_parent_is_not_self", "parent_id IS NULL OR parent_id <> id");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Catalog.Domain.Catalogue.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("active_from");

                    b.Property<DateOnly?>("ActiveTo")
                        .HasColumnType("date")
                        .HasColumnName("active_to");

                    b.Property<bool>("AllowIncomplete")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_incomplete");

                    b.Property<Guid>("CatalogVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_version_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<int>("ExpectedDurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("expected_duration_days");

                    b.Property<string>("IntakeWarning")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("intake_warning");

                    b.Property<Guid>("Key")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_key");

                    b.Property<Guid?>("MeasurementTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameTamil")
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_tamil");

                    b.Property<bool>("NotOrderable")
                        .HasColumnType("boolean")
                        .HasColumnName("not_orderable");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PriceListItemCode")
                        .HasMaxLength(60)
                        .IsUnicode(true)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("price_list_item_code");

                    b.Property<Guid?>("QcChecklistTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("qc_checklist_template_id");

                    b.Property<Guid?>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id")
                        .HasName("pk_service_types");

                    b.HasIndex("CatalogVersionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_service_types_version_key");

                    b.HasIndex("CategoryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_service_types_category_code");

                    b.ToTable("service_types", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_service_types_active_dates_are_ordered", "active_from IS NULL OR active_to IS NULL OR active_to >= active_from");

                            t.HasCheckConstraint("ck_service_types_code_is_well_formed", "code ~ '^[A-Z][A-Z0-9_]*$'");

                            t.HasCheckConstraint("ck_service_types_display_order_is_not_negative", "display_order >= 0");

                            t.HasCheckConstraint("ck_service_types_duration_is_in_range", "expected_duration_days BETWEEN 1 AND 250");
                        });
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "catalog");
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("AvailableAt", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("Tailor360.Modules.Catalog.Domain.Catalogue.Category", b =>
                {
                    b.HasOne("Tailor360.Modules.Catalog.Domain.Catalogue.CatalogVersion", null)
                        .WithMany("Categories")
                        .HasForeignKey("CatalogVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_catalog_versions_catalog_version_id");

                    b.HasOne("Tailor360.Modules.Catalog.Domain.Catalogue.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.OwnsMany("Tailor360.Modules.Catalog.Domain.Catalogue.CategoryBranch", "Branches", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("category_id");

                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("branch_id");

                            b1.HasKey("CategoryId", "BranchId")
                                .HasName("pk_category_branches");

                            b1.ToTable("category_branches", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_category_branches_categories_category_id");
                        });

                    b.Navigation("Branches");
                });

            modelBuilder.Entity("Tailor360.Modules.Catalog.Domain.Catalogue.ServiceType", b =>
                {
                    b.HasOne("Tailor360.Modules.Catalog.Domain.Catalogue.CatalogVersion", null)
                        .WithMany("ServiceTypes")
                        .HasForeignKey("CatalogVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_types_catalog_versions_catalog_version_id");

                    b.HasOne("Tailor360.Modules.Catalog.Domain.Catalogue.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_types_categories_category_id");

                    b.OwnsMany("Tailor360.Modules.Catalog.Domain.Catalogue.ServiceTypeBranch", "Branches", b1 =>
                        {
                            b1.Property<Guid>("ServiceTypeId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_type_id");

                            b1.Property<Guid>("BranchId")
                                .HasColumnType("uuid")
                                .HasColumnName("branch_id");

                            b1.HasKey("ServiceTypeId", "BranchId")
                                .HasName("pk_service_type_branches");

                            b1.ToTable("service_type_branches", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ServiceTypeId")
                                .HasConstraintName("fk_service_type_branches_service_types_service_type_id");
                        });

                    b.OwnsMany("Tailor360.Modules.Catalog.Domain.Catalogue.ServiceTypeDesignGroup", "DesignGroups", b1 =>
                        {
                            b1.Property<Guid>("ServiceTypeId")
                                .HasColumnType("uuid")
                                .HasColumnName("service_type_id");

                            b1.Property<Guid>("DesignOptionGroupId")
                                .HasColumnType("uuid")
                                .HasColumnName("design_option_group_id");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("integer")
                                .HasColumnName("display_order");

                            b1.HasKey("ServiceTypeId", "DesignOptionGroupId")
                                .HasName("pk_service_type_design_groups");

                            b1.ToTable("service_type_design_groups", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ServiceTypeId")
                                .HasConstraintName("fk_service_type_design_groups_service_types_service_type_id");
                        });

                    b.Navigation("Branches");

                    b.Navigation("DesignGroups");
                });

            modelBuilder.Entity("Tailor360.Modules.Catalog.Domain.Catalogue.CatalogVersion", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("ServiceTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
