// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailor360.Modules.Orders.Infrastructure.Persistence;

#nullable disable

namespace Tailor360.Modules.Orders.Infrastructure.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<Guid?>("StartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_order_drafts");

                    b.HasIndex("BranchId", "CustomerId")
                        .HasDatabaseName("ix_order_drafts_branch_customer")
                        .HasFilter("consumed_at IS NULL");

                    b.HasIndex("OrganisationId", "ExpiresAt")
                        .HasDatabaseName("ix_order_drafts_organisation_expiry");

                    b.ToTable("order_drafts", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_drafts_expires_after_it_started", "expires_at > started_at");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_version_id");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category_key");

                    b.Property<Guid?>("DesignSelectionDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("design_selection_draft_id");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("instructions");

                    b.Property<string>("MeasurementIntent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("measurement_intent");

                    b.Property<Guid?>("MeasurementTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_template_id");

                    b.Property<Guid?>("MeasurementVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("measurement_version_id");

                    b.Property<Guid>("OrderDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_draft_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.PrimitiveCollection<Guid[]>("ReferenceMediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("reference_media_ids");

                    b.Property<string>("ServiceTypeKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("service_type_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_order_draft_garments");

                    b.HasIndex("OrderDraftId")
                        .HasDatabaseName("ix_order_draft_garments_unmeasured")
                        .HasFilter("measurement_version_id IS NULL");

                    b.HasIndex("OrderDraftId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ux_order_draft_garments_draft_position");

                    b.ToTable("order_draft_garments", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_draft_garments_measurement_reuse", "(measurement_intent = 'ReuseVersion') = (measurement_version_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarmentDependency", b =>
                {
                    b.Property<Guid>("OrderDraftGarmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_draft_garment_id");

                    b.Property<Guid>("PrerequisiteOrderDraftGarmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("prerequisite_order_draft_garment_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("DeclaredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("declared_at");

                    b.Property<Guid?>("DeclaredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("OrderDraftGarmentId", "PrerequisiteOrderDraftGarmentId", "Kind")
                        .HasName("pk_order_draft_garment_dependencies");

                    b.HasIndex("PrerequisiteOrderDraftGarmentId")
                        .HasDatabaseName("ix_order_draft_garment_dependencies_prerequisite");

                    b.ToTable("order_draft_garment_dependencies", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_draft_garment_dependencies_not_on_itself", "order_draft_garment_id <> prerequisite_order_draft_garment_id");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Estimates.Estimate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtefactChecksum")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("artefact_checksum");

                    b.Property<DateTimeOffset?>("ArtefactRecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("artefact_recorded_at");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("converted_at");

                    b.Property<Guid?>("ConvertedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_by");

                    b.Property<Guid?>("ConvertedToOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("converted_to_order_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("EstimateNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("estimate_number");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("IssuedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("issued_by");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<Guid>("OrderDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_draft_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("superseded_at");

                    b.Property<Guid?>("SupersededBy")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by");

                    b.Property<Guid?>("SupersededByEstimateId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_by_estimate_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Totals", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CalculatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("totals_calculated_at");

                            b1.Property<Guid>("CatalogVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_catalog_version_id");

                            b1.Property<Guid>("PriceListVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_price_list_version_id");

                            b1.Property<Guid>("TaxConfigurationVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_tax_configuration_version_id");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CentralTax", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.CentralTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_central_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_central_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Cess", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.Cess#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_cess_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_cess_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "DiscountTotal", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.DiscountTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_discount_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_discount_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GrandTotal", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.GrandTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_grand_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_grand_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "IntegratedTax", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.IntegratedTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_integrated_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_integrated_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RoundOff", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.RoundOff#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_round_off_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_round_off_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "StateTax", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.StateTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_state_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_state_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Subtotal", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.Subtotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_subtotal_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_subtotal_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TaxableValue", "Tailor360.Modules.Orders.Domain.Estimates.Estimate.Totals#PriceSnapshot.TaxableValue#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_taxable_value_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_taxable_value_currency");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_estimates");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_estimates_customer");

                    b.HasIndex("SupersededByEstimateId")
                        .HasDatabaseName("ix_estimates_superseded_by_estimate_id");

                    b.HasIndex("OrganisationId", "EstimateNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_estimates_organisation_number");

                    b.HasIndex("OrganisationId", "OrderDraftId", "IssuedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_estimates_draft");

                    b.ToTable("estimates", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_estimates_artefact_is_consistent", "(artefact_checksum IS NULL) = (artefact_recorded_at IS NULL)");

                            t.HasCheckConstraint("ck_estimates_converted_is_consistent", "(status = 'Converted') = (converted_at IS NOT NULL) AND (converted_at IS NULL) = (converted_to_order_id IS NULL)");

                            t.HasCheckConstraint("ck_estimates_price_amounts_not_negative", "totals_subtotal_amount >= 0 AND totals_discount_total_amount >= 0 AND totals_taxable_value_amount >= 0 AND totals_central_tax_amount >= 0 AND totals_state_tax_amount >= 0 AND totals_integrated_tax_amount >= 0 AND totals_cess_amount >= 0 AND totals_grand_total_amount >= 0");

                            t.HasCheckConstraint("ck_estimates_price_currency_is_shared", "totals_discount_total_currency = totals_subtotal_currency AND totals_taxable_value_currency = totals_subtotal_currency AND totals_central_tax_currency = totals_subtotal_currency AND totals_state_tax_currency = totals_subtotal_currency AND totals_integrated_tax_currency = totals_subtotal_currency AND totals_cess_currency = totals_subtotal_currency AND totals_round_off_currency = totals_subtotal_currency AND totals_grand_total_currency = totals_subtotal_currency");

                            t.HasCheckConstraint("ck_estimates_price_one_tax_scheme", "NOT (totals_integrated_tax_amount <> 0 AND (totals_central_tax_amount <> 0 OR totals_state_tax_amount <> 0))");

                            t.HasCheckConstraint("ck_estimates_superseded_by_is_not_self", "superseded_by_estimate_id IS NULL OR superseded_by_estimate_id <> id");

                            t.HasCheckConstraint("ck_estimates_superseded_is_consistent", "(status = 'Superseded') = (superseded_at IS NOT NULL) AND (superseded_at IS NULL) = (superseded_by_estimate_id IS NULL)");

                            t.HasCheckConstraint("ck_estimates_validity_not_before_issue", "valid_until >= issued_on");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Jobs.GarmentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CancellationReasonCode")
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cancellation_reason_code");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category_key");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<Guid?>("DeliveredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("delivered_by");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTimeOffset?>("HeldAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("held_at");

                    b.Property<Guid?>("HeldBy")
                        .HasColumnType("uuid")
                        .HasColumnName("held_by");

                    b.Property<Guid?>("HoldApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("hold_approved_by");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hold_reason");

                    b.Property<string>("HoldReasonCode")
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hold_reason_code");

                    b.Property<bool>("IsReadyForDelivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready_for_delivery");

                    b.Property<int>("JobIndex")
                        .HasColumnType("integer")
                        .HasColumnName("job_index");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("job_number");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset?>("ProductionStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("production_started_at");

                    b.Property<Guid?>("ProductionStartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("production_started_by");

                    b.Property<string>("ReadyStateBlocks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ready_state_blocks");

                    b.Property<DateTimeOffset?>("ReadyStateComputedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ready_state_computed_at");

                    b.PrimitiveCollection<Guid[]>("ReferenceMediaIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("reference_media_ids");

                    b.Property<string>("ServiceTypeKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("service_type_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.Property<Guid?>("WorkflowVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_version_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CalculatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("price_calculated_at");

                            b1.Property<Guid>("CatalogVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("price_catalog_version_id");

                            b1.Property<Guid>("PriceListVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("price_price_list_version_id");

                            b1.Property<Guid>("TaxConfigurationVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("price_tax_configuration_version_id");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CentralTax", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.CentralTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_central_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_central_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Cess", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.Cess#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_cess_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_cess_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "DiscountTotal", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.DiscountTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_discount_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_discount_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GrandTotal", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.GrandTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_grand_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_grand_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "IntegratedTax", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.IntegratedTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_integrated_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_integrated_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RoundOff", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.RoundOff#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_round_off_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_round_off_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "StateTax", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.StateTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_state_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_state_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Subtotal", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.Subtotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_subtotal_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_subtotal_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TaxableValue", "Tailor360.Modules.Orders.Domain.Jobs.GarmentJob.Price#PriceSnapshot.TaxableValue#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("price_taxable_value_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("price_taxable_value_currency");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_garment_jobs");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_garment_jobs_ready")
                        .HasFilter("is_ready_for_delivery");

                    b.HasIndex("BranchId", "DueDate")
                        .HasDatabaseName("ix_garment_jobs_due")
                        .HasFilter("status NOT IN ('Delivered', 'Closed', 'Cancelled')");

                    b.HasIndex("OrderId", "JobIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_garment_jobs_order_index");

                    b.HasIndex("OrganisationId", "JobNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_garment_jobs_organisation_number");

                    b.ToTable("garment_jobs", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_garment_jobs_cancelled_is_consistent", "(status = 'Cancelled') = (cancelled_at IS NOT NULL) AND (cancelled_at IS NULL) = (cancellation_reason_code IS NULL)");

                            t.HasCheckConstraint("ck_garment_jobs_delivered_is_consistent", "status <> 'Delivered' OR delivered_at IS NOT NULL");

                            t.HasCheckConstraint("ck_garment_jobs_hold_is_consistent", "(held_at IS NOT NULL) = (hold_reason_code IS NOT NULL) AND (held_at IS NULL) = (hold_reason IS NULL)");

                            t.HasCheckConstraint("ck_garment_jobs_job_index_is_positive", "job_index >= 1");

                            t.HasCheckConstraint("ck_garment_jobs_price_amounts_not_negative", "price_subtotal_amount >= 0 AND price_discount_total_amount >= 0 AND price_taxable_value_amount >= 0 AND price_central_tax_amount >= 0 AND price_state_tax_amount >= 0 AND price_integrated_tax_amount >= 0 AND price_cess_amount >= 0 AND price_grand_total_amount >= 0");

                            t.HasCheckConstraint("ck_garment_jobs_price_currency_is_shared", "price_discount_total_currency = price_subtotal_currency AND price_taxable_value_currency = price_subtotal_currency AND price_central_tax_currency = price_subtotal_currency AND price_state_tax_currency = price_subtotal_currency AND price_integrated_tax_currency = price_subtotal_currency AND price_cess_currency = price_subtotal_currency AND price_round_off_currency = price_subtotal_currency AND price_grand_total_currency = price_subtotal_currency");

                            t.HasCheckConstraint("ck_garment_jobs_price_one_tax_scheme", "NOT (price_integrated_tax_amount <> 0 AND (price_central_tax_amount <> 0 OR price_state_tax_amount <> 0))");

                            t.HasCheckConstraint("ck_garment_jobs_ready_has_been_computed", "is_ready_for_delivery = false OR ready_state_computed_at IS NOT NULL");

                            t.HasCheckConstraint("ck_garment_jobs_ready_has_no_blocks", "is_ready_for_delivery = false OR jsonb_array_length(ready_state_blocks) = 0");

                            t.HasCheckConstraint("ck_garment_jobs_workflow_pin_is_consistent", "(production_started_at IS NULL) = (workflow_version_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Jobs.JobDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DeclaredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("declared_at");

                    b.Property<Guid?>("DeclaredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("declared_by");

                    b.Property<Guid>("GarmentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("garment_job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("PrerequisiteGarmentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("prerequisite_garment_job_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_job_dependencies");

                    b.HasIndex("PrerequisiteGarmentJobId")
                        .HasDatabaseName("ix_job_dependencies_prerequisite");

                    b.HasIndex("GarmentJobId", "PrerequisiteGarmentJobId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_job_dependencies_job_prerequisite_kind");

                    b.ToTable("job_dependencies", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_job_dependencies_not_on_itself", "garment_job_id <> prerequisite_garment_job_id");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("CancellationReasonCode")
                        .HasMaxLength(40)
                        .IsUnicode(true)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cancellation_reason_code");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("delivered_at");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("EstimateId")
                        .HasColumnType("uuid")
                        .HasColumnName("estimate_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrderDraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_draft_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("order_number");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset?>("ProductionStartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("production_started_at");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Totals", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CalculatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("totals_calculated_at");

                            b1.Property<Guid>("CatalogVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_catalog_version_id");

                            b1.Property<Guid>("PriceListVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_price_list_version_id");

                            b1.Property<Guid>("TaxConfigurationVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_tax_configuration_version_id");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CentralTax", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.CentralTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_central_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_central_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Cess", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.Cess#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_cess_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_cess_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "DiscountTotal", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.DiscountTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_discount_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_discount_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GrandTotal", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.GrandTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_grand_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_grand_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "IntegratedTax", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.IntegratedTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_integrated_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_integrated_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RoundOff", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.RoundOff#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_round_off_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_round_off_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "StateTax", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.StateTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_state_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_state_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Subtotal", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.Subtotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_subtotal_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_subtotal_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TaxableValue", "Tailor360.Modules.Orders.Domain.Orders.Order.Totals#PriceSnapshot.TaxableValue#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_taxable_value_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_taxable_value_currency");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("EstimateId")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_estimate")
                        .HasFilter("estimate_id IS NOT NULL");

                    b.HasIndex("CustomerId", "ConfirmedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_orders_customer");

                    b.HasIndex("OrganisationId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_organisation_number");

                    b.ToTable("orders", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_orders_cancelled_is_consistent", "(status = 'Cancelled') = (cancelled_at IS NOT NULL) AND (cancelled_at IS NULL) = (cancellation_reason_code IS NULL) AND (cancelled_at IS NULL) = (cancellation_reason IS NULL)");

                            t.HasCheckConstraint("ck_orders_price_amounts_not_negative", "totals_subtotal_amount >= 0 AND totals_discount_total_amount >= 0 AND totals_taxable_value_amount >= 0 AND totals_central_tax_amount >= 0 AND totals_state_tax_amount >= 0 AND totals_integrated_tax_amount >= 0 AND totals_cess_amount >= 0 AND totals_grand_total_amount >= 0");

                            t.HasCheckConstraint("ck_orders_price_currency_is_shared", "totals_discount_total_currency = totals_subtotal_currency AND totals_taxable_value_currency = totals_subtotal_currency AND totals_central_tax_currency = totals_subtotal_currency AND totals_state_tax_currency = totals_subtotal_currency AND totals_integrated_tax_currency = totals_subtotal_currency AND totals_cess_currency = totals_subtotal_currency AND totals_round_off_currency = totals_subtotal_currency AND totals_grand_total_currency = totals_subtotal_currency");

                            t.HasCheckConstraint("ck_orders_price_one_tax_scheme", "NOT (totals_integrated_tax_amount <> 0 AND (totals_central_tax_amount <> 0 OR totals_state_tax_amount <> 0))");

                            t.HasCheckConstraint("ck_orders_revision_number_is_positive", "revision_number >= 1");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Orders.OrderRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<Guid?>("SupersededEstimateId")
                        .HasColumnType("uuid")
                        .HasColumnName("superseded_estimate_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Totals", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("CalculatedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("totals_calculated_at");

                            b1.Property<Guid>("CatalogVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_catalog_version_id");

                            b1.Property<Guid>("PriceListVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_price_list_version_id");

                            b1.Property<Guid>("TaxConfigurationVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("totals_tax_configuration_version_id");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "CentralTax", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.CentralTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_central_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_central_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Cess", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.Cess#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_cess_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_cess_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "DiscountTotal", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.DiscountTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_discount_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_discount_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "GrandTotal", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.GrandTotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_grand_total_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_grand_total_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "IntegratedTax", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.IntegratedTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_integrated_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_integrated_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "RoundOff", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.RoundOff#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_round_off_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_round_off_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "StateTax", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.StateTax#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_state_tax_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_state_tax_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Subtotal", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.Subtotal#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_subtotal_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_subtotal_currency");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "TaxableValue", "Tailor360.Modules.Orders.Domain.Orders.OrderRevision.Totals#PriceSnapshot.TaxableValue#Money", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("totals_taxable_value_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("totals_taxable_value_currency");
                                });
                        });

                    b.HasKey("Id")
                        .HasName("pk_order_revisions");

                    b.HasIndex("OrderId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_order_revisions_order_number");

                    b.ToTable("order_revisions", "orders", t =>
                        {
                            t.HasCheckConstraint("ck_order_revisions_number_is_positive", "revision_number >= 1");

                            t.HasCheckConstraint("ck_order_revisions_price_amounts_not_negative", "totals_subtotal_amount >= 0 AND totals_discount_total_amount >= 0 AND totals_taxable_value_amount >= 0 AND totals_central_tax_amount >= 0 AND totals_state_tax_amount >= 0 AND totals_integrated_tax_amount >= 0 AND totals_cess_amount >= 0 AND totals_grand_total_amount >= 0");

                            t.HasCheckConstraint("ck_order_revisions_price_currency_is_shared", "totals_discount_total_currency = totals_subtotal_currency AND totals_taxable_value_currency = totals_subtotal_currency AND totals_central_tax_currency = totals_subtotal_currency AND totals_state_tax_currency = totals_subtotal_currency AND totals_integrated_tax_currency = totals_subtotal_currency AND totals_cess_currency = totals_subtotal_currency AND totals_round_off_currency = totals_subtotal_currency AND totals_grand_total_currency = totals_subtotal_currency");

                            t.HasCheckConstraint("ck_order_revisions_price_one_tax_scheme", "NOT (totals_integrated_tax_amount <> 0 AND (totals_central_tax_amount <> 0 OR totals_state_tax_amount <> 0))");
                        });
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "orders");
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("AvailableAt", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "orders");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarment", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Drafts.OrderDraft", null)
                        .WithMany("Garments")
                        .HasForeignKey("OrderDraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_draft_garments_order_drafts_order_draft_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarmentDependency", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarment", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("OrderDraftGarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_draft_garment_dependencies_order_draft_garments_order");

                    b.HasOne("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarment", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteOrderDraftGarmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_draft_garment_dependencies_order_draft_garments_prere");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Estimates.Estimate", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Estimates.Estimate", null)
                        .WithMany()
                        .HasForeignKey("SupersededByEstimateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_estimates_estimates_superseded_by_estimate_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Jobs.GarmentJob", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Orders.Order", null)
                        .WithMany("Jobs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_garment_jobs_orders_order_id");

                    b.OwnsOne("Tailor360.Modules.Orders.Domain.Snapshots.DesignSnapshot", "Design", b1 =>
                        {
                            b1.Property<Guid>("GarmentJobId")
                                .HasColumnType("uuid")
                                .HasColumnName("garment_job_id");

                            b1.Property<Guid>("CatalogVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("catalog_version_id");

                            b1.Property<string>("CategoryKey")
                                .IsRequired()
                                .HasMaxLength(40)
                                .IsUnicode(true)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("category_key");

                            b1.Property<string>("CategoryLabel")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("category_label");

                            b1.Property<string>("ConditionalNotes")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("conditional_notes");

                            b1.Property<DateTimeOffset>("FrozenAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("frozen_at");

                            b1.Property<string>("GarmentInstructions")
                                .HasMaxLength(2000)
                                .IsUnicode(true)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("garment_instructions");

                            b1.Property<string>("Selections")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("selections");

                            b1.Property<string>("ServiceTypeKey")
                                .IsRequired()
                                .HasMaxLength(40)
                                .IsUnicode(true)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("service_type_key");

                            b1.Property<string>("ServiceTypeLabel")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("service_type_label");

                            b1.HasKey("GarmentJobId")
                                .HasName("pk_design_snapshots");

                            b1.ToTable("design_snapshots", "orders");

                            b1.WithOwner()
                                .HasForeignKey("GarmentJobId")
                                .HasConstraintName("fk_design_snapshots_garment_jobs_id");
                        });

                    b.OwnsOne("Tailor360.Modules.Orders.Domain.Snapshots.MeasurementSnapshot", "Measurements", b1 =>
                        {
                            b1.Property<Guid>("GarmentJobId")
                                .HasColumnType("uuid")
                                .HasColumnName("garment_job_id");

                            b1.Property<DateTimeOffset>("FrozenAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("frozen_at");

                            b1.Property<Guid>("MeasurementTemplateId")
                                .HasColumnType("uuid")
                                .HasColumnName("measurement_template_id");

                            b1.Property<Guid?>("MeasurementVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("measurement_version_id");

                            b1.Property<DateTimeOffset>("TakenAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("taken_at");

                            b1.Property<Guid?>("TakenBy")
                                .HasColumnType("uuid")
                                .HasColumnName("taken_by");

                            b1.Property<Guid>("TemplateVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("template_version_id");

                            b1.Property<string>("Values")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("values");

                            b1.Property<int>("VersionNumber")
                                .HasColumnType("integer")
                                .HasColumnName("version_number");

                            b1.HasKey("GarmentJobId")
                                .HasName("pk_measurement_snapshots");

                            b1.ToTable("measurement_snapshots", "orders", t =>
                                {
                                    t.HasCheckConstraint("ck_measurement_snapshots_version_number_is_positive", "version_number >= 1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("GarmentJobId")
                                .HasConstraintName("fk_measurement_snapshots_garment_jobs_id");
                        });

                    b.Navigation("Design")
                        .IsRequired();

                    b.Navigation("Measurements")
                        .IsRequired();
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Jobs.JobDependency", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Jobs.GarmentJob", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("GarmentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_dependencies_garment_jobs_garment_job_id");

                    b.HasOne("Tailor360.Modules.Orders.Domain.Jobs.GarmentJob", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteGarmentJobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_job_dependencies_garment_jobs_prerequisite_garment_job_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Orders.Order", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Estimates.Estimate", null)
                        .WithMany()
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_estimates_estimate_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Orders.OrderRevision", b =>
                {
                    b.HasOne("Tailor360.Modules.Orders.Domain.Orders.Order", null)
                        .WithMany("Revisions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_revisions_orders_order_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraft", b =>
                {
                    b.Navigation("Garments");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Drafts.OrderDraftGarment", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Jobs.GarmentJob", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Tailor360.Modules.Orders.Domain.Orders.Order", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
