// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailor360.Modules.Customers.Infrastructure.Persistence;

#nullable disable

namespace Tailor360.Modules.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260908143249_AddCustomerExports")]
    partial class AddCustomerExports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentPurpose", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_consent_purposes");

                    b.HasIndex("OrganisationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_consent_purposes_organisation_key");

                    b.ToTable("consent_purposes", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PurposeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose_key");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source");

                    b.Property<int>("WordingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("wording_version");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("CustomerId", "PurposeKey", "RecordedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_consent_records_customer_purpose_recorded");

                    b.ToTable("consent_records", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentWording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<Guid>("PurposeId")
                        .HasColumnType("uuid")
                        .HasColumnName("purpose_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_consent_wordings");

                    b.HasIndex("PurposeId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_consent_wordings_purpose_version");

                    b.ToTable("consent_wordings", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line");

                    b.Property<string>("AlternatePhoneE164")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("alternate_phone_e164");

                    b.Property<string>("AlternatePhoneLastSix")
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("alternate_phone_last_six");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_number");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(true)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(true)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language");

                    b.Property<string>("Locality")
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locality");

                    b.Property<DateTimeOffset?>("MergedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("merged_at");

                    b.Property<Guid?>("MergedIntoCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_into_customer_id");

                    b.Property<string>("NativeName")
                        .HasMaxLength(160)
                        .IsUnicode(true)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("native_name");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalised_name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("OwningBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("owning_branch_id");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("PhoneLastSix")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("phone_last_six");

                    b.Property<string>("Postcode")
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("postcode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("MergedIntoCustomerId")
                        .HasDatabaseName("ix_customers_merged_into")
                        .HasFilter("merged_into_customer_id IS NOT NULL");

                    b.HasIndex("OrganisationId", "AlternatePhoneLastSix")
                        .HasDatabaseName("ix_customers_alternate_phone_last_six")
                        .HasFilter("alternate_phone_last_six IS NOT NULL");

                    b.HasIndex("OrganisationId", "CustomerNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_organisation_customer_number");

                    b.HasIndex("OrganisationId", "NativeName")
                        .HasDatabaseName("ix_customers_native_name")
                        .HasFilter("native_name IS NOT NULL");

                    b.HasIndex("OrganisationId", "NormalisedName")
                        .HasDatabaseName("ix_customers_normalised_name");

                    b.HasIndex("OrganisationId", "PhoneLastSix")
                        .HasDatabaseName("ix_customers_phone_last_six");

                    b.ToTable("customers", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customers_alternate_phone_is_e164", "alternate_phone_e164 IS NULL OR alternate_phone_e164 ~ '^\\+[1-9][0-9]{7,14}$'");

                            t.HasCheckConstraint("ck_customers_deactivated_at_matches_status", "(status = 'Deactivated') = (deactivated_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_customers_merged_into_is_consistent", "(merged_into_customer_id IS NULL) = (merged_at IS NULL)");

                            t.HasCheckConstraint("ck_customers_merged_into_is_deactivated", "merged_into_customer_id IS NULL OR status = 'Deactivated'");

                            t.HasCheckConstraint("ck_customers_merged_into_is_not_self", "merged_into_customer_id IS NULL OR merged_into_customer_id <> id");

                            t.HasCheckConstraint("ck_customers_phone_is_e164", "phone_e164 ~ '^\\+[1-9][0-9]{7,14}$'");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("NormalisedValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalised_value");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_customer_aliases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_aliases_customer_id");

                    b.HasIndex("NormalisedValue")
                        .HasDatabaseName("ix_customer_aliases_normalised_value");

                    b.ToTable("customer_aliases", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerBranchVisibility", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.HasKey("CustomerId", "BranchId")
                        .HasName("pk_customer_branch_visibility");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_customer_branch_visibility_branch");

                    b.ToTable("customer_branch_visibility", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerExport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ByteCount")
                        .HasColumnType("integer")
                        .HasColumnName("byte_count");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("classification");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<byte[]>("Document")
                        .HasColumnType("bytea")
                        .HasColumnName("document");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_code");

                    b.Property<int>("DocumentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("document_version");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("generated_at");

                    b.Property<Guid?>("GeneratedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by");

                    b.Property<DateTimeOffset?>("LastDownloadedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_downloaded_at");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PurgeReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purge_reason");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("purged_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customer_exports");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_customer_exports_pending_purge")
                        .HasFilter("purged_at IS NULL");

                    b.HasIndex("CustomerId", "GeneratedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_customer_exports_live_by_customer")
                        .HasFilter("purged_at IS NULL");

                    b.ToTable("customer_exports", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customer_exports_expires_after_generated", "expires_at > generated_at");

                            t.HasCheckConstraint("ck_customer_exports_purge_is_consistent", "(purged_at IS NULL) = (purge_reason IS NULL) AND (purged_at IS NULL OR document IS NULL)");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerMerge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AliasesRecorded")
                        .HasColumnType("integer")
                        .HasColumnName("aliases_recorded");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("MergedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("merged_at");

                    b.Property<Guid?>("MergedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_by");

                    b.Property<Guid>("MergedCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("merged_customer_id");

                    b.Property<string>("MergedCustomerNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("merged_customer_number");

                    b.Property<Guid>("NumberAliasId")
                        .HasColumnType("uuid")
                        .HasColumnName("number_alias_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SurvivorCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("survivor_customer_id");

                    b.Property<int>("VisibilityBranchesAdded")
                        .HasColumnType("integer")
                        .HasColumnName("visibility_branches_added");

                    b.HasKey("Id")
                        .HasName("pk_customer_merges");

                    b.HasIndex("MergedCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_customer_merges_merged_customer");

                    b.HasIndex("SurvivorCustomerId", "MergedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_customer_merges_survivor_merged_at");

                    b.ToTable("customer_merges", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Deduplication.DuplicateCandidateDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CandidateCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_customer_id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("decision");

                    b.Property<Guid?>("MergeId")
                        .HasColumnType("uuid")
                        .HasColumnName("merge_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.PrimitiveCollection<string[]>("Reasons")
                        .IsRequired()
                        .HasColumnType("character varying(40)[]")
                        .HasColumnName("reasons");

                    b.Property<Guid>("SubjectCustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_customer_id");

                    b.HasKey("Id")
                        .HasName("pk_duplicate_candidates");

                    b.HasIndex("CandidateCustomerId")
                        .HasDatabaseName("ix_duplicate_candidates_candidate_customer_id");

                    b.HasIndex("MergeId")
                        .HasDatabaseName("ix_duplicate_candidates_merge_id");

                    b.HasIndex("SubjectCustomerId", "DecidedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_duplicate_candidates_subject_decided_at");

                    b.ToTable("duplicate_candidates", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.PrimitiveCollection<string[]>("AllowedChannels")
                        .IsRequired()
                        .HasColumnType("character varying(20)[]")
                        .HasColumnName("allowed_channels");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "QuietHours", "Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences.QuietHours#QuietHours", b1 =>
                        {
                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone")
                                .HasColumnName("quiet_hours_end");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone")
                                .HasColumnName("quiet_hours_start");
                        });

                    b.HasKey("CustomerId")
                        .HasName("pk_communication_preferences");

                    b.ToTable("communication_preferences", "customers");
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("HandlerName")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_name");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId", "HandlerName")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "customers");
                });

            modelBuilder.Entity("Tailor360.Platform.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("available_at");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .IsUnicode(true)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("lease_owner");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at");

                    b.HasIndex("AvailableAt", "AggregateId")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentRecord", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentWording", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Consent.ConsentPurpose", null)
                        .WithMany("Wordings")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_wordings_consent_purposes_purpose_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_customers_customers_merged_into_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerAlias", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany("Aliases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_aliases_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerBranchVisibility", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany("Visibility")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_branch_visibility_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerExport", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_exports_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerMerge", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("MergedCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_merges_customers_merged_customer_id");

                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("SurvivorCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_merges_customers_survivor_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Deduplication.DuplicateCandidateDecision", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CandidateCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_candidates_customers_candidate_customer_id");

                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.CustomerMerge", null)
                        .WithMany()
                        .HasForeignKey("MergeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_duplicate_candidates_customer_merges_merge_id");

                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("SubjectCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_candidates_customers_subject_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithOne()
                        .HasForeignKey("Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_communication_preferences_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentPurpose", b =>
                {
                    b.Navigation("Wordings");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Visibility");
                });
#pragma warning restore 612, 618
        }
    }
}
