// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tailor360.Modules.Customers.Infrastructure.Persistence;

#nullable disable

namespace Tailor360.Modules.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260908003058_AddConsentAndCommunicationPreferences")]
    partial class AddConsentAndCommunicationPreferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentPurpose", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_retired");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_consent_purposes");

                    b.HasIndex("OrganisationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_consent_purposes_organisation_key");

                    b.ToTable("consent_purposes", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<string>("PurposeKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose_key");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source");

                    b.Property<int>("WordingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("wording_version");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("CustomerId", "PurposeKey", "RecordedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_consent_records_customer_purpose_recorded");

                    b.ToTable("consent_records", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentWording", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<Guid>("PurposeId")
                        .HasColumnType("uuid")
                        .HasColumnName("purpose_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_consent_wordings");

                    b.HasIndex("PurposeId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_consent_wordings_purpose_version");

                    b.ToTable("consent_wordings", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line");

                    b.Property<string>("AlternatePhoneE164")
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("alternate_phone_e164");

                    b.Property<string>("AlternatePhoneLastSix")
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("alternate_phone_last_six");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(true)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("customer_number");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .IsUnicode(true)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .IsUnicode(true)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language");

                    b.Property<string>("Locality")
                        .HasMaxLength(120)
                        .IsUnicode(true)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locality");

                    b.Property<string>("NativeName")
                        .HasMaxLength(160)
                        .IsUnicode(true)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("native_name");

                    b.Property<string>("NormalisedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalised_name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("OwningBranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("owning_branch_id");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(true)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("PhoneLastSix")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(true)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("phone_last_six");

                    b.Property<string>("Postcode")
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("postcode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("OrganisationId", "AlternatePhoneLastSix")
                        .HasDatabaseName("ix_customers_alternate_phone_last_six")
                        .HasFilter("alternate_phone_last_six IS NOT NULL");

                    b.HasIndex("OrganisationId", "CustomerNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_organisation_customer_number");

                    b.HasIndex("OrganisationId", "NativeName")
                        .HasDatabaseName("ix_customers_native_name")
                        .HasFilter("native_name IS NOT NULL");

                    b.HasIndex("OrganisationId", "NormalisedName")
                        .HasDatabaseName("ix_customers_normalised_name");

                    b.HasIndex("OrganisationId", "PhoneLastSix")
                        .HasDatabaseName("ix_customers_phone_last_six");

                    b.ToTable("customers", "customers", t =>
                        {
                            t.HasCheckConstraint("ck_customers_alternate_phone_is_e164", "alternate_phone_e164 IS NULL OR alternate_phone_e164 ~ '^\\+[1-9][0-9]{7,14}$'");

                            t.HasCheckConstraint("ck_customers_deactivated_at_matches_status", "(status = 'Deactivated') = (deactivated_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_customers_phone_is_e164", "phone_e164 ~ '^\\+[1-9][0-9]{7,14}$'");
                        });
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("NormalisedValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalised_value");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<Guid?>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_customer_aliases");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_customer_aliases_customer_id");

                    b.HasIndex("NormalisedValue")
                        .HasDatabaseName("ix_customer_aliases_normalised_value");

                    b.ToTable("customer_aliases", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerBranchVisibility", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("added_at");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("added_by");

                    b.HasKey("CustomerId", "BranchId")
                        .HasName("pk_customer_branch_visibility");

                    b.HasIndex("BranchId")
                        .HasDatabaseName("ix_customer_branch_visibility_branch");

                    b.ToTable("customer_branch_visibility", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.PrimitiveCollection<string[]>("AllowedChannels")
                        .IsRequired()
                        .HasColumnType("character varying(20)[]")
                        .HasColumnName("allowed_channels");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(true)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("language");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "QuietHours", "Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences.QuietHours#QuietHours", b1 =>
                        {
                            b1.Property<TimeOnly>("End")
                                .HasColumnType("time without time zone")
                                .HasColumnName("quiet_hours_end");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone")
                                .HasColumnName("quiet_hours_start");
                        });

                    b.HasKey("CustomerId")
                        .HasName("pk_communication_preferences");

                    b.ToTable("communication_preferences", "customers");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentRecord", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentWording", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Consent.ConsentPurpose", null)
                        .WithMany("Wordings")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_wordings_consent_purposes_purpose_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerAlias", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany("Aliases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_aliases_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.CustomerBranchVisibility", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithMany("Visibility")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_branch_visibility_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences", b =>
                {
                    b.HasOne("Tailor360.Modules.Customers.Domain.Customers.Customer", null)
                        .WithOne()
                        .HasForeignKey("Tailor360.Modules.Customers.Domain.Preferences.CommunicationPreferences", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_communication_preferences_customers_customer_id");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Consent.ConsentPurpose", b =>
                {
                    b.Navigation("Wordings");
                });

            modelBuilder.Entity("Tailor360.Modules.Customers.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Visibility");
                });
#pragma warning restore 612, 618
        }
    }
}
