/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one staff account for administration. */
        get: operations["GetStaffUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close a staff account, ending its sessions and remembered devices. */
        post: operations["DeactivateStaffUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen a closed account as an invitation, with no password and no second factor. */
        post: operations["ReactivateStaffUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/reinstate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lift a suspension so the account may sign in again. */
        post: operations["ReinstateStaffUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/reset-mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the account's second factor and end its sessions. */
        post: operations["ResetStaffUserMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End every session the account holds, leaving its standing unchanged. */
        post: operations["RevokeStaffUserSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend a staff account and end its sessions. */
        post: operations["SuspendStaffUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/antiforgery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue the anti-forgery token pair for this browser session. */
        get: operations["GetAntiForgeryToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer the first factor and start a session. */
        post: operations["SignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the session this request is being made under. */
        post: operations["SignOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End every session on the caller's account. */
        post: operations["SignOutEverywhere"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a second-factor challenge with an authenticator or recovery code. */
        post: operations["AnswerMultiFactorChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enrol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start enrolling an authenticator and return the QR link and manual key. */
        post: operations["BeginMultiFactorEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/enrol/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an authenticator with a code and issue the recovery codes. */
        post: operations["ConfirmMultiFactorEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Print a fresh sheet of recovery codes, destroying the previous sheet. */
        post: operations["ReissueRecoveryCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the passkeys registered against the caller's account. */
        get: operations["ListPasskeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/assert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a passkey, which satisfies both factors. */
        post: operations["CompletePasskeyAssertion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/assert/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a passkey sign-in and return the WebAuthn request options. */
        post: operations["BeginPasskeyAssertion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finish registering a passkey. */
        post: operations["CompletePasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/register/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start registering a passkey and return the WebAuthn creation options. */
        post: operations["BeginPasskeyRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/passkeys/{passkeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one of the caller's passkeys. */
        delete: operations["RemovePasskey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Spend a recovery link and set a new password. */
        post: operations["ConfirmPasswordRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recovery/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask for a password recovery link. */
        post: operations["RequestPasswordRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the caller's account, preferences and session expiry. */
        get: operations["GetCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the devices the caller's account is signed in on. */
        get: operations["ListSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** End one session on the caller's account. */
        delete: operations["RevokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report the running build, the supported client range and the environment. */
        get: operations["GetVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountSecurityPayload: {
            factors: components["schemas"]["FactorAvailabilityPayload"];
            /** Format: date-time */
            lastStrongAuthenticationAt: null | string;
            mfaEnrolment: string;
            mfaSatisfied: boolean;
            mustChangePassword: boolean;
            /** Format: int32 */
            unusedRecoveryCodes: number | string;
        };
        AntiForgeryTokenResponse: {
            headerName: string;
            token: string;
        };
        CurrentUserResponse: {
            /** Format: uuid */
            branchId: null | string;
            displayName: string;
            email: string;
            /** Format: uuid */
            organisationId: string;
            permissions: string[];
            preferences: components["schemas"]["PreferencesPayload"];
            security: components["schemas"]["AccountSecurityPayload"];
            session: components["schemas"]["SessionExpiryPayload"];
            status: string;
            /** Format: uuid */
            userId: string;
            userName: string;
        };
        FactorAvailabilityPayload: {
            authenticator: boolean;
            passkey: boolean;
            recoveryCode: boolean;
        };
        JsonElement: unknown;
        MfaEnrolmentConfirmationPayload: {
            code: null | string;
        };
        MfaEnrolmentStartedPayload: {
            accountName: string;
            /** Format: int32 */
            digits: number | string;
            issuer: string;
            manualEntryKey: string;
            otpAuthUri: string;
            /** Format: int32 */
            periodSeconds: number | string;
        };
        MultiFactorChallengeRequest: {
            code: null | string;
            factor: null | string;
            /** @default false */
            rememberDevice: boolean;
        };
        MultiFactorChallengeResponse: {
            deviceRemembered: boolean;
            /** Format: int32 */
            remainingRecoveryCodes: number | string;
            session: components["schemas"]["SessionExpiryPayload"];
            shouldReissueRecoveryCodes: boolean;
        };
        PasskeyAssertionRequest: {
            ceremonyId: null | string;
            credential: components["schemas"]["JsonElement"];
        };
        PasskeyChallengeResponse: {
            ceremonyId: string;
            /** Format: date-time */
            expiresAt: string;
            options: components["schemas"]["JsonElement"];
        };
        PasskeyPayload: {
            /** Format: date-time */
            createdAt: string;
            isBackedUp: boolean;
            label: string;
            /** Format: date-time */
            lastUsedAt: null | string;
            /** Format: uuid */
            passkeyId: string;
        };
        PasskeyRegistrationRequest: {
            ceremonyId: null | string;
            credential: components["schemas"]["JsonElement"];
            label: null | string;
        };
        PreferencesPayload: {
            density: string;
            landingRoute: null | string;
            locale: string;
            reducedMotion: boolean;
            theme: string;
            timeZoneId: string;
        };
        /**
         * Problem details
         * @description RFC 9457 problem details. Every failure is reported in this shape, and never as a stack trace, an exception message or a bare status code.
         */
        ProblemDetails: {
            /** @description The stable error code, `<module>.<kebab-case-reason>` — for example `idempotency.key-reused`. This is what a client branches on. */
            code: string;
            /** @description The correlation identifier of the request, echoed so a support call can name it. */
            correlationId?: string;
            /** @description The same token in `ETag` form, ready to be sent back as `If-Match`. */
            currentEtag?: null | string;
            /** @description The aggregate's current concurrency token, on a version conflict, so the client can re-read and merge without a second round trip. */
            currentVersion?: null | string;
            /** @description What went wrong on this occurrence, in words a person can act on. */
            detail?: null | string;
            /** @description Field errors, keyed by the field's name in the request payload. Present on validation failures only. */
            errors?: null | {
                [key: string]: string[];
            };
            /** @description The request path this occurrence refers to. */
            instance?: null | string;
            /** @description True when repeating the identical request may succeed. A retry of a command reuses the same `Idempotency-Key`. */
            retryable?: null | boolean;
            /**
             * Format: int32
             * @description The HTTP status code, repeated so the body is self-contained.
             */
            status: number;
            /** @description A short, human-readable summary of the problem type. */
            title: string;
            /**
             * Format: uri
             * @description The problem type, as `urn:tailor360:problem:<code>`. Stable across releases; a client may branch on it.
             */
            type: string;
        };
        ReasonPayload: {
            reason: null | string;
        };
        RecoveryAcceptedPayload: {
            message: string;
        };
        RecoveryCodesPayload: {
            recoveryCodes: string[];
        };
        RecoveryCompletedPayload: {
            multiFactorStillRequired: boolean;
            mustChangePassword: boolean;
            /** Format: int32 */
            sessionsRevoked: number | string;
        };
        RecoveryConfirmationPayload: {
            newPassword: null | string;
            token: null | string;
        };
        RecoveryRequestPayload: {
            email: null | string;
        };
        SessionExpiryPayload: {
            /** Format: date-time */
            absoluteExpiresAt: string;
            /** Format: date-time */
            idleExpiresAt: string;
            mfaSatisfied: boolean;
            /** Format: int32 */
            warningLeadSeconds: number | string;
        };
        SessionPayload: {
            /** Format: date-time */
            absoluteExpiresAt: string;
            /** Format: date-time */
            createdAt: string;
            deviceLabel: string;
            /** Format: date-time */
            idleExpiresAt: string;
            ipAddress: null | string;
            isCurrent: boolean;
            /** Format: date-time */
            lastSeenAt: string;
            mfaSatisfied: boolean;
            /** Format: uuid */
            sessionId: string;
        };
        SignInRequest: {
            captchaResponse?: null | string;
            identifier: null | string;
            password: null | string;
        };
        SignInResponse: {
            displayName: string;
            factors: components["schemas"]["FactorAvailabilityPayload"];
            mustChangePassword: boolean;
            session: components["schemas"]["SessionExpiryPayload"];
            step: string;
            /** Format: uuid */
            userId: string;
        };
        SignOutEverywhereResponse: {
            /** Format: int32 */
            sessionsEnded: number | string;
        };
        StaffUserPayload: {
            /** Format: date-time */
            createdAt: string;
            displayName: string;
            email: string;
            /** Format: uuid */
            homeBranchId: null | string;
            /** Format: date-time */
            lastSignInAt: null | string;
            mfaEnrolment: string;
            status: string;
            /** Format: uuid */
            userId: string;
            userName: string;
            version: string;
        };
        VersionResponse: {
            api: string;
            commit?: null | string;
            current: string;
            environment: string;
            minimumClient: string;
            schemaVersion: string;
        };
    };
    responses: {
        /** @description The request was not valid. The body is problem details with per-field `errors` when the failure is a validation failure. */
        BadRequest: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The caller holds a session but not the permission, the branch reach or the session assurance this operation requires. The refusal is audited. */
        Forbidden: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The request failed unexpectedly. The body carries the problem type and the correlation identifier and nothing else — never a stack trace, never an exception message. */
        InternalServerError: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description There is no such resource, or none this caller may see. The two are deliberately indistinguishable, so that the identifier space cannot be probed. */
        NotFound: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The rate-limit policy this operation declares refused the request. `Retry-After` says when it is worth trying again. */
        TooManyRequests: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description There is no live session, or the one presented has expired or been revoked. The client re-authenticates in place and retries the request with the same `Idempotency-Key`. */
        Unauthorized: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The request body was not `application/json`. */
        UnsupportedMediaType: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The client build declared in `X-Client-Version` is older than the minimum this server supports. Reloading collects the current build; repeating the request does not help. The body carries `minimumClient` and `current`. */
        UpgradeRequired: {
            headers: {
                "X-Correlation-Id": components["headers"]["X-Correlation-Id"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description How many seconds to wait before retrying. */
        "Retry-After": number;
        /** @description The correlation identifier of this request. It is accepted on the request and echoed on every response, and it is the identifier a support call names. */
        "X-Correlation-Id": string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetStaffUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    DeactivateStaffUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Resigned; last working day was 5 September."
                 *     }
                 */
                "application/json": components["schemas"]["ReasonPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            426: components["responses"]["UpgradeRequired"];
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ReactivateStaffUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Rejoined the shop; identity confirmed in person by the branch manager."
                 *     }
                 */
                "application/json": components["schemas"]["ReasonPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            426: components["responses"]["UpgradeRequired"];
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ReinstateStaffUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Returned from unpaid leave; the manager confirmed the start date."
                 *     }
                 */
                "application/json": components["schemas"]["ReasonPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            426: components["responses"]["UpgradeRequired"];
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ResetStaffUserMfa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Lost the phone holding the authenticator; identity confirmed in person."
                 *     }
                 */
                "application/json": components["schemas"]["ReasonPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            426: components["responses"]["UpgradeRequired"];
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    RevokeStaffUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Tablet left on a bus; signing every device out while it is recovered."
                 *     }
                 */
                "application/json": components["schemas"]["ReasonPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            426: components["responses"]["UpgradeRequired"];
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SuspendStaffUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Left the company on 5 September; access withdrawn at the manager's request."
                 *     }
                 */
                "application/json": components["schemas"]["ReasonPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffUserPayload"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            415: components["responses"]["UnsupportedMediaType"];
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            426: components["responses"]["UpgradeRequired"];
            /** @description Precondition Required */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetAntiForgeryToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AntiForgeryTokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "captchaResponse": null,
                 *       "identifier": "counter.demo",
                 *       "password": "example-passphrase-not-a-real-credential"
                 *     }
                 */
                "application/json": components["schemas"]["SignInRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SignOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    SignOutEverywhere: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignOutEverywhereResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    AnswerMultiFactorChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "code": "000000",
                 *       "factor": "totp",
                 *       "rememberDevice": false
                 *     }
                 */
                "application/json": components["schemas"]["MultiFactorChallengeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MultiFactorChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    BeginMultiFactorEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaEnrolmentStartedPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ConfirmMultiFactorEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "code": "000000"
                 *     }
                 */
                "application/json": components["schemas"]["MfaEnrolmentConfirmationPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ReissueRecoveryCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ListPasskeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyPayload"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CompletePasskeyAssertion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "ceremonyId": "0192f3c1-9b1e-7a44-9a1b-1f9a0c2e77d1",
                 *       "credential": {
                 *         "id": "ZXhhbXBsZS1jcmVkZW50aWFsLWlkZW50aWZpZXI",
                 *         "rawId": "ZXhhbXBsZS1jcmVkZW50aWFsLWlkZW50aWZpZXI",
                 *         "response": {
                 *           "authenticatorData": "ZXhhbXBsZS1hdXRoZW50aWNhdG9yLWRhdGE",
                 *           "clientDataJSON": "ZXhhbXBsZS1jbGllbnQtZGF0YQ",
                 *           "signature": "ZXhhbXBsZS1zaWduYXR1cmU",
                 *           "userHandle": null
                 *         },
                 *         "type": "public-key"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PasskeyAssertionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    BeginPasskeyAssertion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    CompletePasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "ceremonyId": "0192f3c1-9b1e-7a44-9a1b-1f9a0c2e77d1",
                 *       "credential": {
                 *         "id": "ZXhhbXBsZS1jcmVkZW50aWFsLWlkZW50aWZpZXI",
                 *         "rawId": "ZXhhbXBsZS1jcmVkZW50aWFsLWlkZW50aWZpZXI",
                 *         "response": {
                 *           "attestationObject": "ZXhhbXBsZS1hdHRlc3RhdGlvbi1vYmplY3Q",
                 *           "clientDataJSON": "ZXhhbXBsZS1jbGllbnQtZGF0YQ"
                 *         },
                 *         "type": "public-key"
                 *       },
                 *       "label": "Counter tablet"
                 *     }
                 */
                "application/json": components["schemas"]["PasskeyRegistrationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    BeginPasskeyRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasskeyChallengeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    RemovePasskey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                passkeyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ConfirmPasswordRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "newPassword": "example-passphrase-not-a-real-credential",
                 *       "token": "bm90LWEtcmVhbC1yZWNvdmVyeS10b2tlbg"
                 *     }
                 */
                "application/json": components["schemas"]["RecoveryConfirmationPayload"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCompletedPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    RequestPasswordRecovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "counter.demo@example.invalid"
                 *     }
                 */
                "application/json": components["schemas"]["RecoveryRequestPayload"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryAcceptedPayload"];
                };
            };
            400: components["responses"]["BadRequest"];
            415: components["responses"]["UnsupportedMediaType"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    ListSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPayload"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    RevokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
